[tool.poetry]
name = "mcp-test"
version = "0.1.0"
description = "A simple Hello World project"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"